version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: itcenter-image
    container_name: it-center-app
    ports:
      - "5000:80"
    links:
      - mariadb
  mariadb:
    image: mariadb:10.11.3
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=ITCenterDb